export const USER_REGISTER_PENDING = 'USER_REGISTER_PENDING';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_LOGIN_PENDING = 'USER_LOGIN_PENDING';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const GET_USER_DETAILS_PENDING = 'GET_USER_DETAILS_PENDING';
export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_ERROR = 'USER_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';

export const GET_DATA_PENDING = 'GET_DATA_PENDING';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';

// Todo: create these dynamically...
export const GET_CATEGORIES_PENDING = 'GET_CATEGORIES_PENDING';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const CATEGORIES_UPDATE_PENDING = 'CATEGORIES_UPDATE_PENDING';
export const CATEGORIES_UPDATE_SUCCESS = 'CATEGORIES_UPDATE_SUCCESS';
export const CATEGORIES_CREATE_PENDING = 'CATEGORIES_CREATE_PENDING';
export const CATEGORIES_CREATE_SUCCESS = 'CATEGORIES_CREATE_SUCCESS';
export const CATEGORIES_DELETE_PENDING = 'CATEGORIES_DELETE_PENDING';
export const CATEGORIES_DELETE_SUCCESS = 'CATEGORIES_DELETE_SUCCESS';
export const CATEGORIES_SHOW_ERROR = 'CATEGORIES_SHOW_ERROR';
export const CATEGORIES_DISMISS_ERROR = 'CATEGORIES_DISMISS_ERROR';

export const GET_INCOME_PENDING = 'GET_INCOME_PENDING';
export const GET_INCOME_SUCCESS = 'GET_INCOME_SUCCESS';
export const INCOME_UPDATE_PENDING = 'INCOME_UPDATE_PENDING';
export const INCOME_UPDATE_SUCCESS = 'INCOME_UPDATE_SUCCESS';
export const INCOME_CREATE_PENDING = 'INCOME_CREATE_PENDING';
export const INCOME_CREATE_SUCCESS = 'INCOME_CREATE_SUCCESS';
export const INCOME_DELETE_PENDING = 'INCOME_DELETE_PENDING';
export const INCOME_DELETE_SUCCESS = 'INCOME_DELETE_SUCCESS';
export const INCOME_SHOW_ERROR = 'INCOME_SHOW_ERROR';
export const INCOME_DISMISS_ERROR = 'INCOME_DISMISS_ERROR';

export const GET_EXPENSES_PENDING = 'GET_EXPENSES_PENDING';
export const GET_EXPENSES_SUCCESS = 'GET_EXPENSES_SUCCESS';
export const EXPENSES_UPDATE_PENDING = 'EXPENSES_UPDATE_PENDING';
export const EXPENSES_UPDATE_SUCCESS = 'EXPENSES_UPDATE_SUCCESS';
export const EXPENSES_CREATE_PENDING = 'EXPENSES_CREATE_PENDING';
export const EXPENSES_CREATE_SUCCESS = 'EXPENSES_CREATE_SUCCESS';
export const EXPENSES_DELETE_PENDING = 'EXPENSES_DELETE_PENDING';
export const EXPENSES_DELETE_SUCCESS = 'EXPENSES_DELETE_SUCCESS';
export const EXPENSES_SHOW_ERROR = 'EXPENSES_SHOW_ERROR';
export const EXPENSES_DISMISS_ERROR = 'EXPENSES_DISMISS_ERROR';