export const USER_REGISTER_PENDING = 'USER_REGISTER_PENDING';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_LOGIN_PENDING = 'USER_LOGIN_PENDING';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const GET_USER_DETAILS_PENDING = 'GET_USER_DETAILS_PENDING';
export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_ERROR = 'USER_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';

export const GET_DATA_PENDING = 'GET_DATA_PENDING';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';

// Todo: create these dynamically...
export const GET_CATEGORIES_PENDING = 'GET_CATEGORIES_PENDING';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const CATEGORIES_UPDATE_PENDING = 'CATEGORIES_UPDATE_PENDING';
export const CATEGORIES_UPDATE_SUCCESS = 'CATEGORIES_UPDATE_SUCCESS';
export const CATEGORIES_CREATE_PENDING = 'CATEGORIES_CREATE_PENDING';
export const CATEGORIES_CREATE_SUCCESS = 'CATEGORIES_CREATE_SUCCESS';


export const GET_INCOME_SUCCESS = 'GET_INCOME_SUCCESS';
export const UPDATE_INCOME_PENDING = 'UPDATE_INCOME_PENDING';
export const UPDATE_INCOME_SUCCESS = 'UPDATE_INCOME_SUCCESS';

export const GET_EXPENSES_SUCCESS = 'GET_EXPENSES_SUCCESS';
export const UPDATE_EXPENSES_PENDING = 'UPDATE_EXPENSES_PENDING';
export const UPDATE_EXPENSES_SUCCESS = 'UPDATE_EXPENSES_SUCCESS';